# Generated by Django 4.1.2 on 2022-10-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('text', models.TextField(blank=True, max_length=999)),
                ('publication', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('article_kind', models.CharField(choices=[('NS', 'Not selected'), ('SN', 'Scientific'), ('IN', 'Informational'), ('RW', 'Rewiew')], default='NS', max_length=2)),
                ('slug', models.SlugField(default='', null=True)),
            ],
        ),
    ]
