# Generated by Django 4.1.2 on 2022-11-04 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_app', '0002_article_rating_alter_article_article_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_kind',
            field=models.CharField(choices=[('Not selected', 'Not selected'), ('Scinefic', 'Scientific'), ('Review', 'Rewiew'), ('Informational', 'Informational')], default='Not selected', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication',
            field=models.BooleanField(default=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
