# Generated by Django 4.1.2 on 2022-11-04 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_app', '0003_alter_article_article_kind_alter_article_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_kind',
            field=models.CharField(choices=[('Informational', 'Informational'), ('Review', 'Rewiew'), ('Scinefic', 'Scientific'), ('Not selected', 'Not selected')], default='Not selected', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
