# Generated by Django 4.1.2 on 2022-11-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_app', '0005_profile_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_kind',
            field=models.CharField(choices=[('Scinefic', 'Scientific'), ('Informational', 'Informational'), ('Not selected', 'Not selected'), ('Review', 'Rewiew')], default='Not selected', max_length=20),
        ),
    ]
