# Generated by Django 4.1.2 on 2022-11-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_app', '0006_profile_registration_date_alter_article_article_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='des',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_kind',
            field=models.CharField(choices=[('Scinefic', 'Scientific'), ('Review', 'Rewiew'), ('Not selected', 'Not selected'), ('Informational', 'Informational')], default='Not selected', max_length=20),
        ),
    ]
