# Generated by Django 4.1.2 on 2022-11-04 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_app', '0011_alter_article_article_kind_alter_article_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Famele')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monkey_app.profile'),
        ),
    ]
