# Generated by Django 4.1.2 on 2022-11-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_app', '0014_article_article_views_alter_article_article_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_dislike',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='article_like',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_kind',
            field=models.CharField(choices=[('Review', 'Rewiew'), ('Scinefic', 'Scientific'), ('Informational', 'Informational'), ('Not selected', 'Not selected')], default='Not selected', max_length=20),
        ),
    ]
