# Generated by Django 4.1.2 on 2022-11-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_app', '0016_remove_article_article_dislike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_kind',
            field=models.CharField(choices=[('Review', 'Rewiew'), ('Informational', 'Informational'), ('Not selected', 'Not selected'), ('Scinefic', 'Scientific')], default='Not selected', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
