# Generated by Django 4.1.2 on 2022-11-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_app', '0017_alter_article_article_kind_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_kind',
            field=models.CharField(choices=[('Review', 'Rewiew'), ('Scinefic', 'Scientific'), ('Informational', 'Informational'), ('Not selected', 'Not selected')], default='Not selected', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
