# Generated by Django 4.1.2 on 2022-11-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_app', '0018_alter_article_article_kind_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_kind',
            field=models.CharField(choices=[('Not selected', 'Not selected'), ('Informational', 'Informational'), ('Review', 'Rewiew'), ('Scinefic', 'Scientific')], default='Not selected', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
