# Generated by Django 4.1.2 on 2022-11-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_app', '0019_alter_article_article_kind_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_kind',
            field=models.CharField(choices=[('review', 'Review'), ('informational', 'Informational'), ('scinefic', 'Scientific'), ('not selected', 'Not selected')], default='not selected', max_length=20),
        ),
    ]
