# Generated by Django 4.1.2 on 2022-11-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_app', '0020_alter_article_article_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_kind',
            field=models.CharField(choices=[('review', 'Review'), ('scinefic', 'Scientific'), ('not selected', 'Not selected'), ('informational', 'Informational')], default='not selected', max_length=20),
        ),
    ]
