# Generated by Django 4.1.2 on 2022-11-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_app', '0021_remove_article_slug_alter_article_article_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rating',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_kind',
            field=models.CharField(choices=[('informational', 'Informational'), ('not selected', 'Not selected'), ('scinefic', 'Scientific'), ('review', 'Review')], default='not selected', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication',
            field=models.BooleanField(default=True),
        ),
    ]
